# Generated by Django 5.2.3 on 2025-07-05 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, unique=True, verbose_name='Chat ID в Telegram')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('notify_orders', models.BooleanField(default=True, verbose_name='Уведомлять о новых заказах')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь системы')),
            ],
            options={
                'verbose_name': 'Телеграм менеджер',
                'verbose_name_plural': 'Телеграм менеджеры',
            },
        ),
    ]
